### ISSUE TITLE
How to contribute ? 

### ISSUE THREAD

**Issue by 12rambau** [forestdatapartnership/whisp#12]
I finally get the green light from my company to inegrate some of the devs I did in house to this repository so I would like to start contributing. Who should I contact to get a tour of the Whisp thing ? 

where I can be useful: 
- build a robust class based implementation 
- help with the API (I know the company requirements and I already have something in house to share) 
- documentation (you know I love documenting)
- publish whisp as a python lib

**Comment by julesntare** [comment]
Hello @andyarnell, please we need the documentation to run these notebooks. Thanks

**Comment by andyarnell** [comment]
Hi and apologies for the delay in providing documentation. 
Have added a readme. There are areas to flesh out and improve, but this is a start.

**Comment by andyarnell** [comment]
Oh and feel free to highlight areas of confusion or message with more questions.
I plan to add in some more info on user credentials, how to add other input datasets to those used in Whisp (e.g., for a more bespoke analysis). 
I will also document how to run locally or on Google Colab etc (we are aware not all users will want to use the notebooks in the Sepal environment) - although I sense advanced users will be able to do this without guidance anyhow.

**Comment by FlorentScarpaSustaain** [comment]
Hello @andyarnell @jonnvega,

I would also like to contribute to the project as I find it very promising. Would you be available for a chat to discuss the state of things and how to work together?
