### ISSUE TITLE
Inverted latitude and longitude in function 'whisp_stats_as df'

### ISSUE THREAD

**Issue by FlorentScarpaSustaain** [forestdatapartnership/whisp#20]
Hello,

I noticed that the dataframe output from the `whisp_stats_as_df` function contains columns 'Centroid_lat' and 'Centroid_lon' whose coordinates are inverted when compared to the original polygon.

Here is a MWE notebook (provided as a Markdown file) to run in the same 'whisp' folder as the other provided notebooks: [mwe_issue_latlon_whisp.md](https://github.com/user-attachments/files/15514385/mwe_issue_latlon_whisp.md)

Here is the sample GeoJSON file used in the MWE (named as a JSON because GitHub does not recognize GeoJSON, don't forget to rename the extension)
[sample_1ha_poly_CI_forest_cavally.json](https://github.com/user-attachments/files/15514427/sample_1ha_poly_CI_forest_cavally.json)

Notice how the values in the dataframe's columns are inverted when compared with the (lon, lat) coordinates in the roi Polygon

I am not yet familiar enough with the codebase and geemap to fix it myself. Thanks and congrats on this amazing project.

**Comment by andyarnell** [comment]
Thanks Florent. Someone else spotted too. Fixed now.
