### ISSUE TITLE
Add the decision tree columns inclusion/exclusion in the lookup table

### ISSUE THREAD

**Issue by lecrabe** [forestdatapartnership/whisp#23]
Add the decision tree columns inclusion/exclusion in the lookup table

**Comment by andyarnell** [comment]
...and if you want to know how to make and view the lists there are separate functions (in the modules/tidy_tables.py), for compiling each of the 4 indicators from the lookup csv. These functions are also embedded in the "whisp_risk" function for creating default input lists.  
I will add the above info to the readme when i document the risk indicator aspects.
