### ISSUE TITLE
Agstack connection timeout when running imports module

### ISSUE THREAD

**Issue by FlorentScarpaSustaain** [forestdatapartnership/whisp#25]
Running the imports module attempts to start an agstack session. The latter may time out for some reason and result in a TimeoutError.

Although this is expected behaviour when wanting to use agstack, this is not always the case. Users who do not want to connect to agstack should not have to.

**Comment by andyarnell** [comment]
Hi. 
I have shifted the use of start_agstack_session and get_agstack_token to a better home: in the whisp/modules/agstack_to_gee.py in the geo_id_or_ids_to_feature_collection and register_fc_and_append_to_csv functions as default inputs.

**Comment by andyarnell** [comment]
Until asset registry/ agstack issue is resolved it's hard to test the changes to these functions are working ok. but the main issue here is addressed.
